# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Institute')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Institute',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
