# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('AdministerOfDosages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PID', models.IntegerField()),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Sex', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1)),
                ('BirthDate', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('CatalogPath', models.CharField(max_length=100)),
                ('CreationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descritpion', models.CharField(max_length=100)),
                ('Disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('UserMain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('CreateDate', models.DateTimeField()),
                ('Details', models.CharField(max_length=300)),
                ('CatalogPath', models.CharField(max_length=300)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='photography',
            name='Visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.Visit'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.UserProfile'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.Treatment'),
        ),
        migrations.AddField(
            model_name='disease',
            name='Photography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.Photography'),
        ),
    ]
