# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='PIN',
            new_name='PID',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='UserMain',
        ),
    ]
