# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0002_auto_20171115_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='UserMain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
