# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0002_auto_20171122_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PID',
            field=models.IntegerField(unique=True),
        ),
    ]
