# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 21:26
from __future__ import unicode_literals

import Medical.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0003_auto_20171123_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=Medical.models.GetUploadedPath),
            preserve_default=False,
        ),
    ]
