# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0003_auto_20171116_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Institute',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
