# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0005_auto_20171217_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='Image',
            field=models.ImageField(upload_to='result_images/'),
        ),
    ]
