# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0006_auto_20171217_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='result',
            name='Image',
            field=models.ImageField(upload_to='result_images/'),
        ),
    ]
