# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0007_auto_20171217_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='PercentChange',
            field=models.CharField(default='0%', max_length=100),
        ),
        migrations.AddField(
            model_name='result',
            name='Photo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img1', to='Medical.Photography'),
        ),
        migrations.AddField(
            model_name='result',
            name='Photo2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img2', to='Medical.Photography'),
        ),
    ]
